### PR TITLE
fix: timeout and shutdown

### PR DESCRIPTION
**Pull request by stevenh**
Fix `waitForPruneCondition` timeout handling which was not resetting the connection timeout when new connections came in resulting in the reaper shutting down incorrectly.

Don't log `EOF` errors.

Add buffer to connection channels so we don't block the accepting goroutine.

Fixes https://github.com/testcontainers/testcontainers-go/issues/2348

### CODE REVIEW

**Comment by stevenh** [comment]
@mdelapenya any chance you can help get this one across the line, as its causing random failures in testcontainers-go?

**Review by mdelapenya — APPROVED** [review]
LGTM, thanks and sorry for the delay in the review. I've been focused in other tasks regarding testcontainers-go.

Thank you for your time!

**Comment by stevenh** [comment]
> LGTM, thanks and sorry for the delay in the review. I've been focused in other tasks regarding testcontainers-go.
> 
> Thank you for your time!

Thanks for that, most appreciated!

To get this one fully put to bed, what's the release process, as we'll need to a PR against testcontainers-go to bump it to the new version to get this fix?

**Comment by mdelapenya** [comment]
Exactly, I'm planning to create a release of Ryuk soon this week, the 0.7.1

**Comment by stevenh** [comment]
Just checking in on the release @mdelapenya to make sure it doesn't slip though 😃

**Comment by stevenh** [comment]
Hey @mdelapenya just checking in on this, as we're seeing constant test failures on very basic setups due to this, so would really appreciate a new release here and then one for testcontainers-go with the updated image.

If there's anything I can do assist let me know.

**Pull request merged**
